image:
  name: 315962882822.dkr.ecr.us-east-1.amazonaws.com/builder-utils:fosscicli0.7.0-alpine3.9
  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

pipelines:
  branches:
    release/*.*.*:
      - step:
          name: Build and push images
          size: 2x
          caches:
            - docker
          services:
            - docker
          script:
            - export FOSSCI_DEPLOYMENT=test
            - fossci docker build --tag '1-beta.{bb_build_number}' --file 'Dockerfile'
            - fossci docker push --tag '1-beta.{bb_build_number}'
  tags:
    "v*.*.*+*-*":
      - step:
          name: Build and push images
          caches:
            - docker
          services:
            - docker
          script:
            - export FOSSCI_DEPLOYMENT=prd
            - fossci docker build --file 'Dockerfile'
            - fossci docker push

definitions:
  services:
    docker:
      memory: 4096